### ISSUE TITLE
Error: currentBlockData must not be null

### ISSUE THREAD

**Issue by swapnachippagi** [EOSIO/demux-js#59] opened 2018-10-07 15:08 UTC
When am pushing the data into eosio,am getting error:currentBlockData must not be null
```
(node:2986) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
Example app listening on port 4000!
Mongoose default connection open to mongodb://127.0.0.1/TweetDatabase
(node:2986) UnhandledPromiseRejectionWarning: Error: currentBlockData must not be null.
    at NodeosActionReader.<anonymous> (/home/swapna/Documents/decenttwt/backend/node_modules/demux/dist/AbstractActionReader.js:76:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/swapna/Documents/decenttwt/backend/node_modules/demux/dist/AbstractActionReader.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:2986) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2986) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by flux627** [comment] 2018-11-13 21:37
I'm closing this as this seems to be a potential problem with [EOSIO/demux-js-eos](https://github.com/EOSIO/demux-js-eos), and not specifically this repo.

If you still have steps to reproduce this issue, please feel free to create another issue there.

**Closed by flux627** 2018-11-13 21:37 UTC
