### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by jafri** [EOSIO/demux-js#34] opened 2018-08-13 10:17 UTC
https://github.com/EOSIO/demux-js/blob/0f1717f28d06a2c4dca0d2fec595c14e719afa91/src/demux/readers/eos/NodeosActionReader.ts#L28-L37

This code will sometimes silently fail with ```500 - {"code":500,"message":"Internal Service Error","error":{"code":3100002,"name":"unknown_block_exception","what":"Unknown block","details":[{"message":"Could not find block: 10895151","file":"chain_plugin.cpp","line_number":1276,"method":"get_block"}]}}'```

which causes a hard crash at other points in the code

**Comment by chris-allnutt** [comment] 2018-08-13 11:49
Is this while you're processing blocks behind the head block or after full sync?

**Comment by jeffreyssmith2nd** [comment] 2018-08-13 13:13
Possible duplicate of #17

**Comment by flux627** [comment] 2018-08-13 16:56
This is indeed a duplicate. Closing this, follow the original issue for updates.

**Closed by flux627** 2018-08-13 16:56 UTC
